New command! arch will search in archives. Do help for options. Also cleanup

diff --git a/bin/arch b/bin/arch
--- a/bin/arch
+++ b/bin/arch
@@ -1,97 +1,74 @@
 #!/bin/bash
 
-# Warnings about this script
-echo -e "\e[33mWarning: buggy script, beware!\e[0m"
-# issue: args interpreted as commands instead of filter!
+# Define an associative array to store option descriptions
+declare -A option_descriptions=(
+    [" "]="Conduct fuzzy search of archives using fzf"
+    ["--help"]="Display this help message"
+    ["--dev"]="Open the script with $EDITOR"
+    ["edit"]="Edit document"
+    ["tree"]="Display the directory tree"
+    ["warp"]="[Not implemented] cd to chosen directory"
+    ['<command>']="Executes bultin shell command in archives"
+    ['<pattern>']="Searches for pattern in tree"
+)
 
-# TODO: whitelist command manually such as cat, mkdir, touch, edit, rm, etc.
-# Commands to whitelist:
+# config
+archive_path="$HOME/archives"
 
-### --help
+main() {
+    #warning "This is a warning"
+    
+    if [ $# -eq 0 ]; then arch_fzf; fi
 
-## optional switches to eliminate ambiguity
+    case "$1" in
+        help | --help) help ;;
+        -s | -c) execute_command "$@" ;;
+        --dev) open_this_file ;;
+        edit) open_chosen_file ;;
+        tree) arch_tree ;;
+        warp) cd_to_directory ;;
+        echo | mkdir | touch | rmdir | rm | bat | cat | yq | md | jq) execute_command "$@" ;;
+        *) launch_search "$@" ;;
+    esac
 
-### -p to force pattern
-### -c to force command
-
-## else will determine by whitelist
-
-### custom
-####warp: sends main process to that location, while keeping reference to original locatin with export
-####pwd: builtin
-
-### insert
-####mkdir: builtin
-####touch: builtin
-
-### update
-####edit: alias for micro
-
-### delete
-####rmdir: builtin
-####rm: builtin
-
-### select
-####cat: builtin
-####yq: parse yaml
-####md: parse markdown
-# (anything that isn't one of the above is considered pattern.)
-
-# anything else assume it's pattern for filter!
-
-# accidental duplicates, refactor before removing
-archives="$HOME/archives"
-parent_dir="$HOME/archives"
-
-# Function to display usage instructions
-function display_usage() {
-    echo "Usage: $0 [options] [patterns]"
-    echo "Options:"
-    echo "  --help     Display this help message"
-    echo "  -a         Show hidden files"
-    echo "  -s         Display file sizes"
-    echo "  -L <level> Limit the depth of the directory tree"
-    echo "Patterns:"
-    echo "  Specify search patterns to filter directory names"
+    echo -e "\e[31mERROR\e[0m" >&2
+    exit 1
 }
 
-# search flag
-search=0
+# Help function to display usage information and option descriptions
+help() {
+    # ANSI color codes for colors without using \e[33m and \e[31m
+    GREEN='\033[0;32m'
+    BLUE='\033[0;34m'
+    NC='\033[0m' # No Color
 
-# Check if the user provided the --help option ************************************************
-if [[ "$1" == "--help" ]]; then
-    display_usage
+    echo "Usage: $(basename "$0") [OPTIONS]"
+    echo "Options:"
+    for option in "${!option_descriptions[@]}"; do
+        printf "  ${GREEN}%-12s${NC} %s\n" "$option" "${option_descriptions[$option]}"
+    done
     exit 0
-fi
+}
 
-# [select] ************************************************************************************
+warn() { echo -e "\e[33m$@\e[0m"; }
 
-if [ $# -eq 0 ]; then
-    echo "Consider adding limit config"
-    tree $archives
-    exit 0
-fi
+arch_fzf() {
+    output=$(find "$archive_path" -type f | fzf)
+    es="$?"
+    echo "📋 $style1$output$reset"ac
+    echo "$output" | xclip -selection clipboard
+    exit $es
+}
 
-# [Select + filter] Construct the pattern string by joining the arguments with | **************
+open_this_file() {
+    micro $0
+    exit "$?"
+}
 
-pattern=""
-for arg in "$@"; do
-    if [ -z "$pattern" ]; then
-        pattern="*$arg*"
-    else
-        pattern="$pattern|*$arg*"
-    fi
-    search=1
-done
-
-# [create] ($EDITOR $path) ********************************************************************
-
-# not implemented
-
-# [update] If the first argument is 'edit', edit documents in ~/arch **************************
-if [[ "$1" == "edit" ]]; then
+open_chosen_file() {
+    warn Not tested
     # Use eval to expand wildcard pattern in $2
-    files=$(eval "ls -d $HOME/arch/$2")
+    files=$(eval "ls -d $archive_path/$2")
     
     # Check if any files match the pattern
     if [ -n "$files" ]; then
@@ -104,83 +81,43 @@ if [[ "$1" == "edit" ]]; then
         echo -e "\e[31mNo matching files found.\e[0m"
         exit 1
     fi
-fi
+}
 
-# [delete] (rm or rmdir) **********************************************************************
+arch_tree() {
+    tree "$archive_path"
+    exit "$?"
+}
 
-# not implemented
-
-# Anything that doesn't fit above operations can be executed using 'sh' ***********************
-
-# If the first argument is 'sh', execute shell commands inside ~/arch
-if [[ "$1" == "-s" ]]; then
-    # Get the rest of the arguments as shell commands
-    shift
-    # Change directory to ~/arch and execute the provided shell commands
-    (cd "$archives" && eval "$@")
-    exit $?
-fi
-
-# shortcut bypassing 'sh', nevermind
-
-# # Check if the first argument is a valid command
-# if command -v "$1" &>/dev/null; then
-    # # Change directory to the parent directory
-    # cd "$parent_dir" || exit 1
-# 
-    # # Execute the command with the provided arguments
-    # eval "$@"
-    # exit $?
-# else
-    # echo "Command '$1' not found"
-    # exit 1
-# fi
-
-# Execute search if flag is raised ************************************************************
-
-if [ "$search" -eq 1 ]; then
-    # Search using tree command and only display output if found
-    output=$(tree $archives -C --dirsfirst --prune --matchdirs -P "$pattern")
+launch_search() {
+    pattern=""
+    
+    for arg in "$@"; do
+        if [ -z "$pattern" ]; then
+            pattern="*$arg*"
+        else
+            pattern="$pattern|*$arg*"
+        fi
+    done
+    
+    # Search using tree command
+    output=$(tree $archive_path -C --dirsfirst --prune --matchdirs -P "$pattern")
+    
     # Check if the output contains any directories or files
     if [[ $output == *"0 directories, 0 files"* ]]; then
-        exit 1
+        warn "No match."
+        exit 0
     else
         echo "$output"
         exit 0
     fi
-else
-    echo "No search pattern provided."
-    exit 1
-fi
+}
 
-# End of program ==============================================================================
+execute_command() {
+    warn Not tested
+    if [[ $1 == '-c' || $1 == '-s' ]]; then shift ; fi
+    # Change directory to ~/arch and execute the provided shell commands
+    (cd "$archives" && eval "$@")
+    exit $?
+}
 
-#tree --prune arch -P 'iraqi*|car*'
-
-### To implement in future:
-
-# 1. Error Handling:
-# Add checks to handle cases where the specified directory doesn't exist
-# or where the 'tree' command is not available.
-
-# 2. Custom Output:
-# Allow users to specify options for the 'tree' command,
-# such as showing hidden files (-a), displaying file sizes (-s),
-# or limiting the depth of the directory tree (-L).
-
-# 3. Interactive Mode:
-# Implement an interactive mode where users can input search patterns
-# one by one and see the results immediately.
-
-# 4. Documentation:
-# Include a help message (-h or --help) to explain how to use the script
-# and what options are available.
-
-# 5. Logging:
-# Optionally, log the script's activity to a file for record-keeping
-# or debugging purposes.
-
-# 6. Configuration File:
-# Allow users to specify search patterns and other options in a
-# configuration file, making it easier to use the script with
-# predefined settings.
+main "$@"
